apiVersion: v1
kind: Secret
metadata:
  name: bookmedik-secret
type: Opaque
data:
  user_bookmedik: YWRtaW4=  # 'admin' en base64
  pass_bookmedik: YWRtaW4=  # 'admin' en base64
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: cm9vdA==  # 'root' en base64
  MARIADB_USER: YWRtaW4=  # 'admin' en base64
  MARIADB_PASSWORD: YWRtaW4=  # 'admin' en base64
